import { useState, useEffect, useCallback } from 'react';
import { getDayProfile, WEEKLY_RHYTHM } from '@/utils/weeklyRhythm';
import { loadCachedResistance, ResistanceAnalysis } from '@/utils/resistanceTracker';
import { scoreRevenueImpact } from '@/utils/revenueImpact';
import { QUEST_TEMPLATES } from '@/types/questDifficulty';

// ── Types ────────────────────────────────────────────────────────────

export interface SprintPriority {
  id: string;
  objective: string;
  estimatedSprints: number;
  category: string;
}

export interface SprintAllocation {
  thursday: (string | null)[]; // priority IDs or null
  friday: (string | null)[];
  saturday: (string | null)[];
}

export interface WeekSummary {
  questsCompleted: number;
  questsTotal: number;
  completionPct: number;
  xpEarned: number;
  revenueQuestsCompleted: number;
  resistanceTrend: 'improved' | 'stable' | 'declined';
  systemAssessment: string;
}

export interface WeeklyPlan {
  weekId: string; // e.g. "2026-W06"
  createdAt: string;
  priorities: SprintPriority[];
  allocation: SprintAllocation;
  locked: boolean;
  autoGenerated: boolean;
}

// ── Storage ──────────────────────────────────────────────────────────

const PLAN_KEY = 'systemWeeklyPlan';
const PLAN_DISMISSED_KEY = 'systemWeeklyPlanDismissed';
const COMPLETION_HISTORY_KEY = 'systemCompletionHistory';
const CALIBRATED_COMPLETIONS_KEY = 'systemCalibratedCompletions';
const RESISTANCE_PREV_KEY = 'systemResistancePrevScore';

function getCurrentWeekId(): string {
  const now = new Date();
  const jan1 = new Date(now.getFullYear(), 0, 1);
  const weekNum = Math.ceil(((now.getTime() - jan1.getTime()) / 86400000 + jan1.getDay() + 1) / 7);
  return `${now.getFullYear()}-W${String(weekNum).padStart(2, '0')}`;
}

function loadPlan(): WeeklyPlan | null {
  try {
    const stored = localStorage.getItem(PLAN_KEY);
    if (!stored) return null;
    const plan: WeeklyPlan = JSON.parse(stored);
    if (plan.weekId !== getCurrentWeekId()) return null;
    return plan;
  } catch { return null; }
}

function savePlan(plan: WeeklyPlan) {
  localStorage.setItem(PLAN_KEY, JSON.stringify(plan));
}

function isDismissedThisWeek(): boolean {
  try {
    return localStorage.getItem(PLAN_DISMISSED_KEY) === getCurrentWeekId();
  } catch { return false; }
}

function dismissThisWeek() {
  localStorage.setItem(PLAN_DISMISSED_KEY, getCurrentWeekId());
}

// ── Week Summary Computation ─────────────────────────────────────────

function computeWeekSummary(): WeekSummary {
  const weekAgo = new Date();
  weekAgo.setDate(weekAgo.getDate() - 7);

  let questsCompleted = 0;
  let xpEarned = 0;
  let revenueQuestsCompleted = 0;

  // From completion history
  try {
    const stored = localStorage.getItem(COMPLETION_HISTORY_KEY);
    if (stored) {
      const records: { completedAt: string; xpEarned?: number; questId?: string }[] = JSON.parse(stored);
      const recent = records.filter(r => new Date(r.completedAt) >= weekAgo);
      questsCompleted += recent.length;
      xpEarned += recent.reduce((s, r) => s + (r.xpEarned || 0), 0);

      // Count revenue quests
      for (const r of recent) {
        const tpl = QUEST_TEMPLATES.find(t => t.id === r.questId);
        if (tpl) {
          const score = scoreRevenueImpact(tpl);
          if (score.impact === 'direct' || score.impact === 'supporting') {
            revenueQuestsCompleted++;
          }
        }
      }
    }
  } catch { /* ignore */ }

  // Also count calibrated completions
  try {
    const stored = localStorage.getItem(CALIBRATED_COMPLETIONS_KEY);
    if (stored) {
      const records: { completedAt: string; questId: string }[] = JSON.parse(stored);
      const recent = records.filter(r => new Date(r.completedAt) >= weekAgo);
      // Avoid double counting — these might overlap
      const counted = new Set<string>();
      for (const r of recent) {
        const key = `${r.questId}-${r.completedAt.split('T')[0]}`;
        if (!counted.has(key)) {
          counted.add(key);
        }
      }
    }
  } catch { /* ignore */ }

  // Resistance trend
  const resistance = loadCachedResistance();
  let resistanceTrend: 'improved' | 'stable' | 'declined' = 'stable';
  try {
    const prevStr = localStorage.getItem(RESISTANCE_PREV_KEY);
    const prevScore = prevStr ? Number(prevStr) : null;
    const currentScore = resistance?.overallResistanceScore ?? 0;
    if (prevScore !== null) {
      if (currentScore < prevScore - 5) resistanceTrend = 'improved';
      else if (currentScore > prevScore + 5) resistanceTrend = 'declined';
    }
    localStorage.setItem(RESISTANCE_PREV_KEY, String(currentScore));
  } catch { /* ignore */ }

  // Estimate total expected quests (~5/day * 7)
  const questsTotal = Math.max(questsCompleted, 35);
  const completionPct = Math.round((questsCompleted / questsTotal) * 100);

  // System assessment
  let systemAssessment: string;
  if (completionPct >= 80) {
    systemAssessment = 'Strong week. Momentum building.';
  } else if (completionPct >= 60) {
    systemAssessment = 'Decent execution. Room for improvement.';
  } else if (completionPct >= 40) {
    systemAssessment = 'Inconsistent execution. The System expects more this sprint.';
  } else {
    systemAssessment = 'Below baseline. This sprint is critical for recovery.';
  }

  return {
    questsCompleted,
    questsTotal,
    completionPct,
    xpEarned,
    revenueQuestsCompleted,
    resistanceTrend,
    systemAssessment,
  };
}

// ── Priority Auto-Generation ─────────────────────────────────────────

function generatePriorities(resistance: ResistanceAnalysis | null): SprintPriority[] {
  const priorities: SprintPriority[] = [];

  // Priority 1: Highest revenue-impact action
  const revenueTemplates = QUEST_TEMPLATES
    .map(t => ({ tpl: t, score: scoreRevenueImpact(t) }))
    .filter(({ score }) => score.impact === 'direct')
    .sort((a, b) => b.score.score - a.score.score);

  if (revenueTemplates.length > 0) {
    const top = revenueTemplates[0];
    priorities.push({
      id: 'p1',
      objective: top.tpl.name,
      estimatedSprints: Math.max(1, top.tpl.sprintCount),
      category: top.tpl.category,
    });
  }

  // Priority 2: Resistance-based or second revenue action
  if (resistance && resistance.resistancePoints.length > 0) {
    const topResistance = resistance.resistancePoints
      .filter(r => r.pattern === 'category_avoidance')
      .sort((a, b) => b.avoidanceRate - a.avoidanceRate)[0];
    if (topResistance) {
      const tpl = QUEST_TEMPLATES.find(
        t => t.category === topResistance.category && ['A', 'B'].includes(t.difficulty)
      );
      priorities.push({
        id: 'p2',
        objective: tpl ? tpl.name : `Address ${topResistance.category} resistance`,
        estimatedSprints: 2,
        category: topResistance.category,
      });
    }
  }

  if (priorities.length < 2 && revenueTemplates.length > 1) {
    const second = revenueTemplates[1];
    priorities.push({
      id: 'p2',
      objective: second.tpl.name,
      estimatedSprints: Math.max(1, second.tpl.sprintCount),
      category: second.tpl.category,
    });
  }

  // Priority 3: Supporting/growth action
  const supportingTemplates = QUEST_TEMPLATES
    .map(t => ({ tpl: t, score: scoreRevenueImpact(t) }))
    .filter(({ score }) => score.impact === 'supporting')
    .sort((a, b) => b.score.score - a.score.score);

  if (supportingTemplates.length > 0) {
    const sup = supportingTemplates[0];
    priorities.push({
      id: 'p3',
      objective: sup.tpl.name,
      estimatedSprints: Math.max(1, sup.tpl.sprintCount),
      category: sup.tpl.category,
    });
  }

  // Ensure we have at least 3
  while (priorities.length < 3) {
    priorities.push({
      id: `p${priorities.length + 1}`,
      objective: 'Build and ship',
      estimatedSprints: 2,
      category: 'Systems',
    });
  }

  return priorities.slice(0, 3);
}

// ── Trigger Logic ────────────────────────────────────────────────────

export function shouldShowPlanning(): 'wednesday' | 'thursday-fallback' | null {
  const now = new Date();
  const day = now.getDay();
  const hour = now.getHours();
  const plan = loadPlan();

  // Already has a locked plan this week
  if (plan?.locked) return null;
  if (isDismissedThisWeek()) return null;

  // Wednesday 6-10 PM
  if (day === 3 && hour >= 18 && hour < 22) return 'wednesday';

  // Thursday morning (first open) — if no plan exists
  if (day === 4 && hour < 12 && !plan) return 'thursday-fallback';

  return null;
}

// ── Hook ─────────────────────────────────────────────────────────────

export function useWeeklyPlanning() {
  const [showModal, setShowModal] = useState(false);
  const [plan, setPlan] = useState<WeeklyPlan | null>(loadPlan);
  const [trigger, setTrigger] = useState<'wednesday' | 'thursday-fallback' | null>(null);

  // Check trigger on mount
  useEffect(() => {
    const t = shouldShowPlanning();
    if (t) {
      setTrigger(t);
      // Auto-show after brief delay
      const timeout = setTimeout(() => setShowModal(true), 1500);
      return () => clearTimeout(timeout);
    }
  }, []);

  const summary = computeWeekSummary();
  const resistance = loadCachedResistance();
  const autoPriorities = generatePriorities(resistance);

  const defaultAllocation: SprintAllocation = {
    thursday: Array(WEEKLY_RHYTHM[4].maxSprints).fill(null),
    friday: Array(WEEKLY_RHYTHM[5].maxSprints).fill(null),
    saturday: Array(WEEKLY_RHYTHM[6].maxSprints).fill(null),
  };

  const lockPlan = useCallback((priorities: SprintPriority[], allocation: SprintAllocation) => {
    const newPlan: WeeklyPlan = {
      weekId: getCurrentWeekId(),
      createdAt: new Date().toISOString(),
      priorities,
      allocation,
      locked: true,
      autoGenerated: false,
    };
    savePlan(newPlan);
    setPlan(newPlan);
    setShowModal(false);
  }, []);

  const autoLockPlan = useCallback(() => {
    const newPlan: WeeklyPlan = {
      weekId: getCurrentWeekId(),
      createdAt: new Date().toISOString(),
      priorities: autoPriorities,
      allocation: defaultAllocation,
      locked: true,
      autoGenerated: true,
    };
    savePlan(newPlan);
    setPlan(newPlan);
    setShowModal(false);
  }, [autoPriorities, defaultAllocation]);

  const dismiss = useCallback(() => {
    dismissThisWeek();
    setShowModal(false);
  }, []);

  const openPlanning = useCallback(() => {
    setShowModal(true);
  }, []);

  return {
    showModal,
    setShowModal,
    plan,
    trigger,
    summary,
    autoPriorities,
    defaultAllocation,
    lockPlan,
    autoLockPlan,
    dismiss,
    openPlanning,
  };
}
