import { PlayerStats } from './player';

export type QuestDifficulty = 'S' | 'A' | 'B' | 'C' | 'D';

export type QuestCategory = 'Sales' | 'Systems' | 'Creative' | 'Discipline' | 'Network' | 'Wealth' | 'Health' | 'Learning';

export type GeneticTag = 'comt_peak' | 'comt_recovery' | 'actn3_sprint' | 'actn3_rest';

export interface QuestTemplate {
  id: string;
  name: string;
  description: string;
  difficulty: QuestDifficulty;
  category: QuestCategory;
  baseXP: number;
  statBoosts: Partial<Record<keyof PlayerStats, number>>;
  estimatedMinutes: number;
  requiresState: 'push' | 'steady' | 'any';
  sprintCount: number;
  geneticTag?: GeneticTag;
}

// Maps category → primary stat
export const CATEGORY_STAT_MAP: Record<QuestCategory, keyof PlayerStats> = {
  Sales: 'sales',
  Systems: 'systems',
  Creative: 'creative',
  Discipline: 'discipline',
  Network: 'network',
  Wealth: 'wealth',
  Health: 'discipline',
  Learning: 'creative',
};

// Difficulty badge styling
export const DIFFICULTY_BADGE_CONFIG: Record<QuestDifficulty, {
  label: string;
  className: string;
  glow?: string;
}> = {
  S: {
    label: 'S',
    className: 'bg-red-500/20 text-red-400 border-red-500/50',
    glow: '0 0 8px rgba(239,68,68,0.5)',
  },
  A: {
    label: 'A',
    className: 'bg-orange-500/20 text-orange-400 border-orange-500/50',
  },
  B: {
    label: 'B',
    className: 'bg-blue-500/20 text-blue-400 border-blue-500/50',
  },
  C: {
    label: 'C',
    className: 'bg-green-500/20 text-green-400 border-green-500/50',
  },
  D: {
    label: 'D',
    className: 'bg-gray-500/20 text-gray-400 border-gray-500/50',
  },
};

// ── Quest Template Library ───────────────────────────────────────────

export const QUEST_TEMPLATES: QuestTemplate[] = [
  // ── S-RANK (push only, 75-100 XP) ──
  {
    id: 'tpl-cold-call-5',
    name: 'Cold Call 5 Prospects',
    description: 'Make 5 outbound calls to potential Augmentive clients.',
    difficulty: 'S',
    category: 'Sales',
    baseXP: 90,
    statBoosts: { sales: 1, network: 0.3 },
    estimatedMinutes: 90,
    requiresState: 'push',
    sprintCount: 2,
  },
  {
    id: 'tpl-ship-deliverable',
    name: 'Ship a Client Deliverable',
    description: 'Complete and deliver a client-facing artifact or feature.',
    difficulty: 'S',
    category: 'Systems',
    baseXP: 100,
    statBoosts: { systems: 1, wealth: 0.5 },
    estimatedMinutes: 135,
    requiresState: 'push',
    sprintCount: 3,
  },
  {
    id: 'tpl-publish-longform',
    name: 'Publish Long-Form Content',
    description: 'Write and publish a blog post, article, or case study.',
    difficulty: 'S',
    category: 'Creative',
    baseXP: 80,
    statBoosts: { creative: 1, network: 0.3 },
    estimatedMinutes: 90,
    requiresState: 'push',
    sprintCount: 2,
  },
  {
    id: 'tpl-discovery-call',
    name: 'Run a Discovery Call',
    description: 'Conduct a high-stakes sales or discovery call with a prospect.',
    difficulty: 'S',
    category: 'Sales',
    baseXP: 100,
    statBoosts: { sales: 1, network: 0.5 },
    estimatedMinutes: 45,
    requiresState: 'push',
    sprintCount: 1,
    geneticTag: 'comt_peak',
  },
  {
    id: 'tpl-build-automation',
    name: 'Build Complete Automation Workflow',
    description: 'Design and implement a full automation pipeline.',
    difficulty: 'S',
    category: 'Systems',
    baseXP: 95,
    statBoosts: { systems: 1, wealth: 0.3 },
    estimatedMinutes: 135,
    requiresState: 'push',
    sprintCount: 3,
  },

  // ── A-RANK (push or steady, 40-74 XP) ──
  {
    id: 'tpl-outreach-10',
    name: 'Send 10 Outreach Messages',
    description: 'Send 10 personalized outreach messages via LinkedIn or email.',
    difficulty: 'A',
    category: 'Sales',
    baseXP: 50,
    statBoosts: { sales: 0.5, network: 0.3 },
    estimatedMinutes: 45,
    requiresState: 'steady',
    sprintCount: 1,
  },
  {
    id: 'tpl-deep-work-augmentive',
    name: 'Deep Work Sprint: Augmentive Build',
    description: 'One focused 45-minute sprint building Augmentive product.',
    difficulty: 'A',
    category: 'Systems',
    baseXP: 60,
    statBoosts: { systems: 0.5, discipline: 0.3 },
    estimatedMinutes: 45,
    requiresState: 'steady',
    sprintCount: 1,
    geneticTag: 'actn3_sprint',
  },
  {
    id: 'tpl-linkedin-slay',
    name: 'Write LinkedIn Post with SLAY Framework',
    description: 'Craft a LinkedIn post using Story-Lesson-Action-You framework.',
    difficulty: 'A',
    category: 'Creative',
    baseXP: 45,
    statBoosts: { creative: 0.5, network: 0.3 },
    estimatedMinutes: 45,
    requiresState: 'steady',
    sprintCount: 1,
  },
  {
    id: 'tpl-follow-up-warm',
    name: 'Follow Up with 3 Warm Leads',
    description: 'Re-engage 3 prospects who have shown prior interest.',
    difficulty: 'A',
    category: 'Network',
    baseXP: 55,
    statBoosts: { network: 0.5, sales: 0.3 },
    estimatedMinutes: 45,
    requiresState: 'steady',
    sprintCount: 1,
  },
  {
    id: 'tpl-update-financials',
    name: 'Update Financial Tracker',
    description: 'Review income, expenses, and runway projections.',
    difficulty: 'A',
    category: 'Wealth',
    baseXP: 40,
    statBoosts: { wealth: 0.5 },
    estimatedMinutes: 45,
    requiresState: 'steady',
    sprintCount: 1,
  },
  {
    id: 'tpl-optimize-automation',
    name: 'Optimize Existing Automation',
    description: 'Improve speed, reliability, or scope of an existing workflow.',
    difficulty: 'A',
    category: 'Systems',
    baseXP: 50,
    statBoosts: { systems: 0.5 },
    estimatedMinutes: 45,
    requiresState: 'steady',
    sprintCount: 1,
  },

  // ── B-RANK (any mode, 20-39 XP) ──
  {
    id: 'tpl-respond-messages',
    name: 'Review and Respond to All Messages',
    description: 'Clear inbox — reply to all pending DMs, emails, and comments.',
    difficulty: 'B',
    category: 'Network',
    baseXP: 25,
    statBoosts: { network: 0.3 },
    estimatedMinutes: 45,
    requiresState: 'any',
    sprintCount: 1,
  },
  {
    id: 'tpl-exercise-30',
    name: '30-Minute Exercise Session',
    description: 'Complete today\'s scheduled workout.',
    difficulty: 'B',
    category: 'Health',
    baseXP: 30,
    statBoosts: { discipline: 0.5 },
    estimatedMinutes: 30,
    requiresState: 'any',
    sprintCount: 1,
    geneticTag: 'actn3_sprint',
  },
  {
    id: 'tpl-research-competitor',
    name: 'Research One Competitor or Tool',
    description: 'Deep dive into one competitor\'s offering or a new tool.',
    difficulty: 'B',
    category: 'Learning',
    baseXP: 25,
    statBoosts: { creative: 0.3, systems: 0.3 },
    estimatedMinutes: 45,
    requiresState: 'any',
    sprintCount: 1,
  },
  {
    id: 'tpl-document-process',
    name: 'Document a Process or Workflow',
    description: 'Write documentation for a system or SOP.',
    difficulty: 'B',
    category: 'Systems',
    baseXP: 30,
    statBoosts: { systems: 0.3, creative: 0.3 },
    estimatedMinutes: 45,
    requiresState: 'any',
    sprintCount: 1,
  },
  {
    id: 'tpl-engage-linkedin',
    name: 'Engage with 5 LinkedIn Posts',
    description: 'Leave thoughtful comments on 5 posts in your niche.',
    difficulty: 'B',
    category: 'Network',
    baseXP: 20,
    statBoosts: { network: 0.3 },
    estimatedMinutes: 20,
    requiresState: 'any',
    sprintCount: 1,
  },
  {
    id: 'tpl-review-pipeline',
    name: 'Review Pipeline and Prioritize',
    description: 'Audit your sales pipeline and re-rank priorities.',
    difficulty: 'B',
    category: 'Wealth',
    baseXP: 25,
    statBoosts: { wealth: 0.3, sales: 0.3 },
    estimatedMinutes: 30,
    requiresState: 'any',
    sprintCount: 1,
  },

  // ── C-RANK (any mode, 10-19 XP) ──
  {
    id: 'tpl-supplements',
    name: 'Take All Supplements',
    description: 'Complete morning, midday, and evening supplement stacks.',
    difficulty: 'C',
    category: 'Health',
    baseXP: 10,
    statBoosts: { discipline: 0.3 },
    estimatedMinutes: 5,
    requiresState: 'any',
    sprintCount: 0,
  },
  {
    id: 'tpl-walk-15',
    name: '15-Minute Walk',
    description: 'Get outside for a quick walk. Sunlight + movement.',
    difficulty: 'C',
    category: 'Discipline',
    baseXP: 15,
    statBoosts: { discipline: 0.3 },
    estimatedMinutes: 15,
    requiresState: 'any',
    sprintCount: 0,
  },
  {
    id: 'tpl-journal-wins',
    name: 'Journal: 3 Wins from Today',
    description: 'Write down 3 things that went well today.',
    difficulty: 'C',
    category: 'Creative',
    baseXP: 15,
    statBoosts: { creative: 0.3 },
    estimatedMinutes: 10,
    requiresState: 'any',
    sprintCount: 0,
  },
  {
    id: 'tpl-read-20',
    name: 'Read for 20 Minutes',
    description: 'Read a book, article, or research paper for 20 minutes.',
    difficulty: 'C',
    category: 'Learning',
    baseXP: 15,
    statBoosts: { creative: 0.3 },
    estimatedMinutes: 20,
    requiresState: 'any',
    sprintCount: 0,
  },
  {
    id: 'tpl-organize',
    name: 'Organize Workspace',
    description: 'Clean desk, organize files, clear browser tabs.',
    difficulty: 'C',
    category: 'Discipline',
    baseXP: 10,
    statBoosts: { discipline: 0.3 },
    estimatedMinutes: 15,
    requiresState: 'any',
    sprintCount: 0,
  },
  {
    id: 'tpl-review-calendar',
    name: "Review Tomorrow's Calendar",
    description: 'Check tomorrow\'s schedule and prep any materials.',
    difficulty: 'C',
    category: 'Discipline',
    baseXP: 10,
    statBoosts: { discipline: 0.3, systems: 0.3 },
    estimatedMinutes: 10,
    requiresState: 'any',
    sprintCount: 0,
  },

  // ── D-RANK (recovery priority, 5-10 XP) ──
  {
    id: 'tpl-cold-exposure',
    name: 'Cold Exposure: 2 Minutes',
    description: 'Cold shower or ice bath for at least 2 minutes.',
    difficulty: 'D',
    category: 'Health',
    baseXP: 10,
    statBoosts: { discipline: 0.3 },
    estimatedMinutes: 5,
    requiresState: 'any',
    sprintCount: 0,
    geneticTag: 'comt_recovery',
  },
  {
    id: 'tpl-breathing',
    name: '5-Minute Breathing Exercise',
    description: 'Box breathing or Wim Hof method for 5 minutes.',
    difficulty: 'D',
    category: 'Health',
    baseXP: 5,
    statBoosts: { discipline: 0.3 },
    estimatedMinutes: 5,
    requiresState: 'any',
    sprintCount: 0,
  },
  {
    id: 'tpl-hydrate',
    name: 'Hydrate: Drink 32oz Water',
    description: 'Down a full bottle of water. Stay hydrated, hunter.',
    difficulty: 'D',
    category: 'Health',
    baseXP: 5,
    statBoosts: { discipline: 0.3 },
    estimatedMinutes: 2,
    requiresState: 'any',
    sprintCount: 0,
  },
  {
    id: 'tpl-podcast',
    name: 'Listen to One Podcast Episode',
    description: 'Listen to a business, health, or tech podcast.',
    difficulty: 'D',
    category: 'Learning',
    baseXP: 10,
    statBoosts: { creative: 0.3 },
    estimatedMinutes: 30,
    requiresState: 'any',
    sprintCount: 0,
  },
  {
    id: 'tpl-stretch',
    name: 'Stretch for 10 Minutes',
    description: 'Full-body stretch. Counteract desk posture.',
    difficulty: 'D',
    category: 'Health',
    baseXP: 5,
    statBoosts: { discipline: 0.3 },
    estimatedMinutes: 10,
    requiresState: 'any',
    sprintCount: 0,
  },
  {
    id: 'tpl-gratitude-text',
    name: 'Gratitude: Text Someone You Appreciate',
    description: 'Send a genuine message of appreciation to someone.',
    difficulty: 'D',
    category: 'Network',
    baseXP: 10,
    statBoosts: { network: 0.3 },
    estimatedMinutes: 5,
    requiresState: 'any',
    sprintCount: 0,
  },

  // ── Extra templates for variety ──
  {
    id: 'tpl-sprint-break',
    name: '15-Minute Sprint Break',
    description: 'Walk, stretch, or breathe between sprints.',
    difficulty: 'D',
    category: 'Health',
    baseXP: 5,
    statBoosts: { discipline: 0.3 },
    estimatedMinutes: 15,
    requiresState: 'any',
    sprintCount: 0,
    geneticTag: 'actn3_rest',
  },
  {
    id: 'tpl-second-wind',
    name: 'Second Wind: Post-Cold-Exposure Sprint',
    description: 'Leverage post-cold dopamine for one bonus deep work sprint.',
    difficulty: 'A',
    category: 'Systems',
    baseXP: 60,
    statBoosts: { systems: 0.5, discipline: 0.3 },
    estimatedMinutes: 45,
    requiresState: 'steady',
    sprintCount: 1,
    geneticTag: 'comt_recovery',
  },
];
