import { useState, useCallback } from 'react';
import { toast } from 'sonner';
import { Plus, Swords, TrendingUp, ChevronDown, ChevronUp, Trash2, ArrowUp, Zap, X, Download, Loader2 } from 'lucide-react';
import { Shadow, SHADOW_CATEGORIES, ShadowCategory, getCategoryIcon, getTotalArmyPower, getForceMultiplier } from '@/types/shadowArmy';
import { useShadowArmy } from '@/hooks/useShadowArmy';
import { supabase } from '@/integrations/supabase/client';
import { usePlayer } from '@/hooks/usePlayer';
import { getSystemDate } from '@/utils/dayCycleEngine';

interface ShadowEvolution {
  previousPower: number;
  newPower: number;
  evolved: boolean;
  contributionScore: number;
  activationCount: number;
  fractionalPower: number;
}

interface ShadowActivation {
  title: string;
  content: string;
  quickActions: string[];
  evolutionHint: string;
  powerLevelImpact?: string;
  activatedAt: string;
  isScoutReport?: boolean;
  keyFindings?: string[];
  topTools?: { name: string; description: string; leveragePotential: string }[];
  evolution?: ShadowEvolution;
}

const STATUS_COLORS: Record<string, string> = {
  active: 'text-primary border-primary/30',
  dormant: 'text-muted-foreground border-border',
  evolving: 'text-secondary border-secondary/30',
};

function ShadowActivationModal({ shadow, activation, loading, onClose, onActivate }: {
  shadow: Shadow;
  activation: ShadowActivation | null;
  loading: boolean;
  onClose: () => void;
  onActivate: () => void;
}) {
  const handleDownload = () => {
    if (!activation) return;
    const blob = new Blob([`# ${activation.title}\n\n${activation.content}\n\n## Next Steps\n${activation.quickActions.map((a, i) => `${i + 1}. ${a}`).join('\n')}\n\n---\n*Generated by The System — ${shadow.name} (LV ${shadow.power_level})*`], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${shadow.name.replace(/\s+/g, '-').toLowerCase()}-lv${shadow.power_level}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4" onClick={onClose}>
      <div
        className="relative w-full max-w-lg max-h-[80vh] overflow-y-auto rounded-xl border border-primary/30 bg-card p-6 space-y-4"
        style={{ boxShadow: '0 0 40px hsl(270 60% 50% / 0.15)' }}
        onClick={(e) => e.stopPropagation()}
      >
        <button onClick={onClose} className="absolute top-4 right-4 text-muted-foreground hover:text-foreground">
          <X className="h-4 w-4" />
        </button>

        <div className="flex items-center gap-3">
          <span className="text-2xl">{getCategoryIcon(shadow.category)}</span>
          <div>
            <h3 className="font-tech text-sm text-foreground">{shadow.name}</h3>
            <p className="font-mono text-[10px] text-primary">LV {shadow.power_level} · {shadow.category}</p>
          </div>
        </div>

        {loading && (
          <div className="flex flex-col items-center justify-center py-12 space-y-3">
            <Loader2 className="h-8 w-8 text-purple-400 animate-spin" />
            <p className="font-mono text-xs text-purple-400 animate-pulse">Activating shadow...</p>
          </div>
        )}

        {!loading && !activation && (
          <div className="text-center py-8 space-y-4">
            <p className="font-mono text-xs text-muted-foreground">{shadow.description}</p>
            <button
              onClick={onActivate}
              className="inline-flex items-center gap-2 rounded-lg border border-purple-500/40 bg-purple-500/10 px-6 py-3 font-mono text-xs text-purple-400 hover:bg-purple-500/20 hover:border-purple-500/60 transition-all"
            >
              <Zap className="h-4 w-4" />
              ACTIVATE SHADOW
            </button>
            <p className="font-mono text-[9px] text-muted-foreground/50">
              Generates personalized, actionable content scaled to power level.
            </p>
          </div>
        )}

        {activation && (
          <div className="space-y-4">
            <div className="rounded-lg border border-primary/20 bg-muted/20 p-4">
              <h4 className="font-tech text-sm text-primary mb-2">{activation.title}</h4>
              {activation.isScoutReport && (
                <span className="inline-block mb-2 rounded-full border border-cyan-500/30 bg-cyan-500/10 px-2 py-0.5 font-mono text-[9px] text-cyan-400 uppercase tracking-wider">
                  🔍 Recon Report
                </span>
              )}
              <div className="font-mono text-[11px] text-foreground/80 leading-relaxed whitespace-pre-wrap">
                {activation.content}
              </div>
            </div>

            {/* Scout: Key Findings */}
            {activation.isScoutReport && activation.keyFindings && activation.keyFindings.length > 0 && (
              <div className="space-y-2">
                <p className="font-mono text-[9px] tracking-widest text-cyan-400 uppercase">Key Findings</p>
                {activation.keyFindings.map((finding, i) => (
                  <div key={i} className="flex items-start gap-2 rounded-md border border-cyan-500/20 bg-cyan-500/5 p-2.5">
                    <span className="font-mono text-[10px] text-cyan-400 shrink-0">▸</span>
                    <p className="font-mono text-[10px] text-foreground/70">{finding}</p>
                  </div>
                ))}
              </div>
            )}

            {/* Scout: Top Tools */}
            {activation.isScoutReport && activation.topTools && activation.topTools.length > 0 && (
              <div className="space-y-2">
                <p className="font-mono text-[9px] tracking-widest text-cyan-400 uppercase">Intel: Tools & Platforms</p>
                {activation.topTools.map((tool, i) => (
                  <div key={i} className="rounded-md border border-border bg-muted/10 p-2.5">
                    <div className="flex items-center justify-between">
                      <span className="font-mono text-[10px] text-foreground font-semibold">{tool.name}</span>
                      <span className={`font-mono text-[8px] uppercase tracking-wider ${
                        tool.leveragePotential === 'critical' ? 'text-red-400' :
                        tool.leveragePotential === 'high' ? 'text-amber-400' : 'text-muted-foreground'
                      }`}>{tool.leveragePotential}</span>
                    </div>
                    <p className="font-mono text-[9px] text-muted-foreground mt-1">{tool.description}</p>
                  </div>
                ))}
              </div>
            )}

            {activation.quickActions.length > 0 && (
              <div className="space-y-2">
                <p className="font-mono text-[9px] tracking-widest text-primary uppercase">Immediate Actions</p>
                {activation.quickActions.map((action, i) => (
                  <div key={i} className="flex items-start gap-2 rounded-md border border-border bg-muted/10 p-2.5">
                    <span className="font-mono text-[10px] text-primary shrink-0">{i + 1}.</span>
                    <p className="font-mono text-[10px] text-foreground/70">{action}</p>
                  </div>
                ))}
              </div>
            )}

            <div className="rounded-md border border-purple-500/20 bg-purple-500/5 p-3">
              <p className="font-mono text-[9px] tracking-widest text-purple-400 uppercase mb-1">Evolution Preview</p>
              <p className="font-mono text-[10px] text-purple-400/70">{activation.evolutionHint}</p>
            </div>

            <div className="flex gap-2">
              <button
                onClick={onActivate}
                className="flex-1 flex items-center justify-center gap-2 rounded-lg border border-primary/30 bg-primary/10 px-4 py-2.5 font-mono text-[10px] text-primary hover:bg-primary/20 transition-all"
              >
                <Zap className="h-3 w-3" />
                REACTIVATE
              </button>
              <button
                onClick={handleDownload}
                className="flex items-center gap-2 rounded-lg border border-border bg-muted/20 px-4 py-2.5 font-mono text-[10px] text-muted-foreground hover:text-foreground transition-all"
              >
                <Download className="h-3 w-3" />
                DOWNLOAD
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

function ShadowCard({ shadow, onLevelUp, onRemove, onUse }: {
  shadow: Shadow;
  onLevelUp: () => void;
  onRemove: () => void;
  onUse: () => void;
}) {
  return (
    <div className={`rounded-lg border bg-card p-3 transition-all ${STATUS_COLORS[shadow.status]}`}>
      <div className="flex items-start justify-between gap-2">
        <div className="flex items-center gap-2 min-w-0 cursor-pointer" onClick={onUse}>
          <span className="text-lg shrink-0">{getCategoryIcon(shadow.category)}</span>
          <div className="min-w-0">
            <h4 className="font-tech text-sm text-foreground truncate">{shadow.name}</h4>
            {shadow.description && (
              <p className="text-[10px] text-muted-foreground truncate mt-0.5">{shadow.description}</p>
            )}
          </div>
        </div>
        <div className="flex items-center gap-1 shrink-0">
          <span className="font-mono text-[10px] text-primary">LV {shadow.power_level}</span>
        </div>
      </div>
      <div className="flex items-center justify-between mt-2">
        <div className="flex items-center gap-2">
          <span className="font-mono text-[9px] uppercase text-muted-foreground">{shadow.category}</span>
          {shadow.contribution_score > 0 && (
            <span className="font-mono text-[9px] text-secondary">+{shadow.contribution_score}%</span>
          )}
        </div>
        <div className="flex gap-1">
          <button onClick={onUse} className="p-1 rounded hover:bg-purple-500/10 transition-colors" title="Activate">
            <Zap className="h-3 w-3 text-purple-400" />
          </button>
          <button onClick={onLevelUp} className="p-1 rounded hover:bg-primary/10 transition-colors" title="Level Up">
            <ArrowUp className="h-3 w-3 text-primary" />
          </button>
          <button onClick={onRemove} className="p-1 rounded hover:bg-destructive/10 transition-colors" title="Remove">
            <Trash2 className="h-3 w-3 text-muted-foreground hover:text-destructive" />
          </button>
        </div>
      </div>
    </div>
  );
}

function AddShadowForm({ onAdd, onCancel }: {
  onAdd: (name: string, category: ShadowCategory, description?: string) => void;
  onCancel: () => void;
}) {
  const [name, setName] = useState('');
  const [category, setCategory] = useState<ShadowCategory>('automation');
  const [description, setDescription] = useState('');

  return (
    <div className="rounded-lg border border-primary/30 bg-card p-4 space-y-3">
      <p className="font-mono text-[10px] tracking-widest text-primary uppercase">Extract New Shadow</p>
      <input
        type="text"
        value={name}
        onChange={(e) => setName(e.target.value)}
        placeholder="Shadow name..."
        className="w-full rounded-md border border-border bg-background/50 px-3 py-2 font-mono text-xs text-foreground placeholder:text-muted-foreground/50 focus:border-primary/50 focus:outline-none"
        autoFocus
      />
      <div className="grid grid-cols-3 gap-1.5">
        {SHADOW_CATEGORIES.map(cat => (
          <button
            key={cat.value}
            onClick={() => setCategory(cat.value)}
            className={`rounded-md border px-2 py-1.5 font-mono text-[10px] transition-all ${
              category === cat.value
                ? 'border-primary/50 bg-primary/10 text-primary'
                : 'border-border text-muted-foreground hover:border-primary/20'
            }`}
          >
            {cat.icon} {cat.label}
          </button>
        ))}
      </div>
      <input
        type="text"
        value={description}
        onChange={(e) => setDescription(e.target.value)}
        placeholder="Description (optional)..."
        className="w-full rounded-md border border-border bg-background/50 px-3 py-2 font-mono text-[10px] text-foreground placeholder:text-muted-foreground/50 focus:border-primary/50 focus:outline-none"
      />
      <div className="flex gap-2">
        <button
          onClick={() => { if (name.trim()) onAdd(name.trim(), category, description.trim() || undefined); }}
          disabled={!name.trim()}
          className={`flex-1 py-2 rounded-md font-mono text-[10px] tracking-wider transition-all ${
            name.trim() ? 'border border-primary/50 bg-primary/10 text-primary' : 'border border-border text-muted-foreground/40'
          }`}
        >
          EXTRACT
        </button>
        <button onClick={onCancel} className="py-2 px-3 rounded-md font-mono text-[10px] text-muted-foreground/50 hover:text-muted-foreground">
          Cancel
        </button>
      </div>
    </div>
  );
}

interface ShadowArmyPanelProps {
  onShadowAdded?: (name: string) => void;
}

export function ShadowArmyPanel({ onShadowAdded }: ShadowArmyPanelProps = {}) {
  const { shadows, loading, addShadow, removeShadow, levelUp } = useShadowArmy();
  const { player } = usePlayer();
  const [expanded, setExpanded] = useState(false);
  const [adding, setAdding] = useState(false);
  const [activeShadow, setActiveShadow] = useState<Shadow | null>(null);
  const [activation, setActivation] = useState<ShadowActivation | null>(null);
  const [activating, setActivating] = useState(false);

  const totalPower = getTotalArmyPower(shadows);
  const multiplier = getForceMultiplier(shadows);
  const activeShadows = shadows.filter(s => s.status === 'active');

  const handleAdd = async (name: string, category: ShadowCategory, description?: string) => {
    await addShadow(name, category, description);
    setAdding(false);
    onShadowAdded?.(name);
  };

  const handleRemove = async (id: string) => {
    if (confirm('Dissolve this shadow?')) await removeShadow(id);
  };

  const handleActivate = useCallback(async (shadow: Shadow) => {
    setActiveShadow(shadow);
    setActivation(null);
    setActivating(true);

    try {
      const now = new Date();
      const pstNow = new Date(now.toLocaleString('en-US', { timeZone: 'America/Los_Angeles' }));

      const { data, error } = await supabase.functions.invoke('shadow-activate', {
        body: {
          shadow: {
            id: shadow.id,
            name: shadow.name,
            category: shadow.category,
            description: shadow.description,
            power_level: shadow.power_level,
            activationCount: shadow.metadata?.activationCount || 0,
          },
          playerContext: {
            goal: player.goal,
            level: player.level,
            stats: player.stats,
            currentTime: pstNow.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }),
            dayType: pstNow.getDay() >= 0 && pstNow.getDay() <= 3 ? 'work' : 'free',
          },
        },
      });

      if (error) throw error;
      setActivation(data as ShadowActivation);
    } catch (e: any) {
      console.error('Shadow activation failed:', e);
      setActivation({
        title: 'Activation Failed',
        content: 'The shadow could not be activated at this time. Try again.',
        quickActions: [],
        evolutionHint: 'Level up this shadow to unlock stronger activations.',
        activatedAt: new Date().toISOString(),
      });
    } finally {
      setActivating(false);
    }
  }, [player]);

  return (
    <div className="space-y-2">
      {/* Activation Modal */}
      {activeShadow && (
        <ShadowActivationModal
          shadow={activeShadow}
          activation={activation}
          loading={activating}
          onClose={() => { setActiveShadow(null); setActivation(null); }}
          onActivate={() => handleActivate(activeShadow)}
        />
      )}

      {/* Header */}
      <button
        onClick={() => setExpanded(!expanded)}
        className="flex w-full items-center justify-between rounded-lg border border-border bg-card/80 px-4 py-3 transition-colors hover:border-secondary/30"
      >
        <div className="flex items-center gap-2">
          <Swords className="h-4 w-4 text-secondary" />
          <span className="font-tech text-xs text-secondary uppercase tracking-wider">Shadow Army</span>
          <span className="font-mono text-[10px] text-muted-foreground">
            {activeShadows.length} shadows
          </span>
        </div>
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-1">
            <TrendingUp className="h-3 w-3 text-primary" />
            <span className="font-mono text-[10px] text-primary">{multiplier.toFixed(1)}x</span>
          </div>
          <span className="font-mono text-[10px] text-muted-foreground">PWR {totalPower}</span>
          {expanded ? <ChevronUp className="h-3 w-3 text-muted-foreground" /> : <ChevronDown className="h-3 w-3 text-muted-foreground" />}
        </div>
      </button>

      {expanded && (
        <div className="space-y-2 pl-1">
          {loading ? (
            <div className="rounded-lg border border-border bg-card/50 p-4 text-center">
              <span className="font-mono text-[10px] text-muted-foreground animate-pulse">Summoning shadows...</span>
            </div>
          ) : (
            <>
              {/* Stats bar */}
              <div className="flex gap-2">
                {(['automation', 'client', 'content', 'sop', 'skill', 'tool'] as ShadowCategory[]).map(cat => {
                  const count = shadows.filter(s => s.category === cat && s.status === 'active').length;
                  if (count === 0) return null;
                  return (
                    <span key={cat} className="font-mono text-[9px] text-muted-foreground">
                      {getCategoryIcon(cat)}{count}
                    </span>
                  );
                })}
              </div>

              {/* Shadow list */}
              {shadows.map(shadow => (
                <ShadowCard
                  key={shadow.id}
                  shadow={shadow}
                  onLevelUp={() => levelUp(shadow.id)}
                  onRemove={() => handleRemove(shadow.id)}
                  onUse={() => { setActiveShadow(shadow); setActivation(null); }}
                />
              ))}

              {/* Add shadow */}
              {adding ? (
                <AddShadowForm onAdd={handleAdd} onCancel={() => setAdding(false)} />
              ) : (
                <button
                  onClick={() => setAdding(true)}
                  className="flex w-full items-center justify-center gap-2 rounded-lg border border-dashed border-secondary/30 py-3 font-mono text-[10px] text-secondary/60 transition-all hover:border-secondary/50 hover:text-secondary"
                >
                  <Plus className="h-3 w-3" />
                  Extract New Shadow
                </button>
              )}
            </>
          )}
        </div>
      )}
    </div>
  );
}
